<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="index.aspx.cs" Inherits="Lab_3.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Product Manager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <link href="./assets/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
    <form id="form1" runat="server">
    <div class="container">
        <h1 style="text-align:center;">Product Manager  <small>by Cee</small></h1>
        <div class="row" style="text-align:center;padding:10px 0">
        <asp:ObjectDataSource ID="ProductsDataSource" runat="server" SelectMethod="GetProducts" TypeName="Lab_3.Products" InsertMethod="InsertProduct" DeleteMethod="DeleteProduct" UpdateMethod="UpdateProduct">
            <DeleteParameters>
                <asp:Parameter Name="id" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="id" Type="String" />
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="price" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="id" Type="String" />
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="price" Type="String" />
            </UpdateParameters>
        </asp:ObjectDataSource>
        <div class="table-responsive" style="padding-top:10px;">
        <asp:GridView ID="GridView1" runat="server" class="table table-bordered table-hover" style="text-align:center;" AutoGenerateColumns="False" DataSourceID="ProductsDataSource" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id">
            <Columns>
                <asp:BoundField DataField="id" HeaderText="序号" SortExpression="id"/>
                <asp:BoundField DataField="name" HeaderText="名称" SortExpression="name"/>
                <asp:BoundField DataField="price" HeaderText="价格" SortExpression="price"/>
            </Columns>
        </asp:GridView>
        </div>
        </div>
        <div class="row" style="text-align:center;padding:10px 0">
        <div class="table-responsive" style="padding-top:10px;">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
        <asp:DetailsView ID="DetailsView1" runat="server" class="table table-bordered table-hover" AutoGenerateRows="False" DataSourceID="ProductsDataSource">
            <Fields>
                <asp:BoundField DataField="id" HeaderText="id" SortExpression="id" />
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                <asp:BoundField DataField="price" HeaderText="price" SortExpression="price" />
                <asp:CommandField ShowInsertButton="True" />
            </Fields>
        </asp:DetailsView>
        </div>
        <div class="col-lg-4"></div>
        </div>
        </div>
    </div>
    </form>
</body>
</html>
